---
depends_on: []
kind: pipeline
name: starlark
steps:
- commands:
  - buildifier --mode=check .drone.star
  image: owncloudci/bazel-buildifier
  name: starlark-format
- commands:
  - buildifier --mode=fix .drone.star
  - git diff
  image: owncloudci/bazel-buildifier
  name: starlark-diff
  when:
    status:
    - failure
trigger:
  ref:
  - refs/heads/main
  - refs/pull/**
type: docker
---
depends_on:
- starlark
kind: pipeline
name: kubernetes
steps:
- commands:
  - helm lint charts/owncloud
  image: alpine/helm:latest
  name: helm-lint
- commands:
  - helm template charts/owncloud -f charts/owncloud/values-ci-testing.yaml > ocis-ci-templated.yaml
  depends_on:
  - helm-lint
  image: alpine/helm:latest
  name: helm-template
- commands:
  - /kube-linter
  - lint
  - ocis-ci-templated.yaml
  depends_on:
  - helm-template
  image: stackrox/kube-linter:latest
  name: kube-lint
- commands:
  - /kubeconform
  - -kubernetes-version
  - 1.20.0
  - -summary
  - -strict
  - ocis-ci-templated.yaml
  depends_on:
  - kube-lint
  image: ghcr.io/yannh/kubeconform:master
  name: kubeconform-1.20.0
- commands:
  - /kubeconform
  - -kubernetes-version
  - 1.21.0
  - -summary
  - -strict
  - ocis-ci-templated.yaml
  depends_on:
  - kube-lint
  image: ghcr.io/yannh/kubeconform:master
  name: kubeconform-1.21.0
- commands:
  - /kubeconform
  - -kubernetes-version
  - 1.22.0
  - -summary
  - -strict
  - ocis-ci-templated.yaml
  depends_on:
  - kube-lint
  image: ghcr.io/yannh/kubeconform:master
  name: kubeconform-1.22.0
- commands:
  - /kubeconform
  - -kubernetes-version
  - 1.23.0
  - -summary
  - -strict
  - ocis-ci-templated.yaml
  depends_on:
  - kube-lint
  image: ghcr.io/yannh/kubeconform:master
  name: kubeconform-1.23.0
- commands:
  - /kubeconform
  - -kubernetes-version
  - 1.24.0
  - -summary
  - -strict
  - ocis-ci-templated.yaml
  depends_on:
  - kube-lint
  image: ghcr.io/yannh/kubeconform:master
  name: kubeconform-1.24.0
trigger:
  ref:
  - refs/heads/master
  - refs/pull/**
type: docker
