---
apiVersion: v2
name: owncloud
version: 0.0.0-devel
description: ownCloud Server Helm chart
appVersion: 10.13.2
home: https://owncloud.com/
keywords:
  - owncloud
  - files
  - collaboration
  - sharing
maintainers:
  - name: ownCloud GmbH
    email: devops@owncloud.com
    url: https://owncloud.com
type: application
kubeVersion: "~1.24.0-0 || ~1.25.0-0 || ~1.26.0-0 || ~1.27.0-0 || ~1.28.0-0" # if this changes, also kubernetesVersions in .drone.star needs to be changed
sources:
  - https://github.com/owncloud-docker/helm-charts
  - https://github.com/owncloud-docker/server
  - https://github.com/owncloud/core
