---
replicaCount: 1

owncloud:
  domain: owncloud.chart.example
  username: owncloud
  password: owncloud
  volume_apps: /mnt/data/apps
  volume_config: /mnt/data/config
  volume_files: /mnt/data/files
  volume_root: /mnt/data
  configExtra:
    openid-connect:
      auto-provision:
        enabled: true
        email-claim: "email"
        display-name-claim: "name"
      provider-url: "https://example.com"
      client-id: "myclientid"
      client-secret: "mysecret"
      autoRedirectOnLoginPage: false
      mode: "email"
      scopes: []
      use-access-token-payload-for-user-info: false

mariadb:
  enabled: false

externalDatabase:
  type: ""
  host: ""
  port: 3306
  name: owncloud
  user: owncloud
  password: owncloud

persistence:
  enabled: true
  owncloud:
    accessMode:
      - ReadWriteOnce
    size: 20Gi
    nfs: {}

redis:
  enabled: false

image:
  repository: docker.io/owncloud/server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 10.11

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  readOnlyRootFilesystem: false

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: "owncloud.chart.example"
      paths: ["/*"]
      servicePort: 80
  tls:
    - hosts:
        - "owncloud.chart.example"
      secretName: owncloud

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
