apiVersion: v1
kind: ConfigMap
metadata:
  name: owncloud-config
  namespace: default
data:
  configmap.config.php: |
    <?php
    $CONFIG = json_decode('{{ toPrettyJson .Values.owncloud.configExtra | nindent 4 }}
    ', true);
