---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "owncloud.fullname" . }}
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
  annotations:
    ignore-check.kube-linter.io/run-as-non-root : "ownCloud does not support non-root containers"
    ignore-check.kube-linter.io/no-read-only-root-fs : "ownCloud need to write /etc/environment on startup"
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "owncloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ print .Values.owncloud.configExtra | sha256sum }}
        checksum/env-config: {{ include (print .Template.BasePath "/envconfigmap.yaml") . | sha256sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "owncloud.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "owncloud.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "init-{{ .Chart.Name }}-mkdir"
          image: {{ template "owncloud.image" . }}
          command: ['sh', '-c', "mkdir -p {{ .Values.owncloud.volume.apps }} {{ .Values.owncloud.volume.config }} {{ .Values.owncloud.volume.files }} {{ .Values.owncloud.volume.sessions }}"]
          volumeMounts:
            - name: owncloud-data
              mountPath: {{ .Values.owncloud.volume.root }}
          resources:
            {{- toYaml .Values.initResources | nindent 12 }}
        {{- if not .Values.owncloud.skipChown }}
        - name: "init-{{ .Chart.Name }}-chown"
          image: {{ template "owncloud.image" . }}
          command: ['sh', '-c', "chown -R www-data:www-data {{ .Values.owncloud.volume.root }}"]
          volumeMounts:
            - name: owncloud-data
              mountPath: {{ .Values.owncloud.volume.root }}
          resources:
            {{- toYaml .Values.initResources | nindent 12 }}
        {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "owncloud.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: owncloud-env-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status.php
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.owncloud.domain | quote }}
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /status.php
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.owncloud.domain | quote }}
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: owncloud-data
              mountPath: {{ .Values.owncloud.volume.root }}
            - name: config-volume
              mountPath: {{ .Values.owncloud.volume.config }}/configmap.config.php
              subPath: configmap.config.php
            {{- with .Values.owncloud.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: owncloud-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
          {{- if .Values.persistence.owncloud.existingClaim }}
            claimName: {{ .Values.persistence.owncloud.existingClaim }}
          {{- else }}
            claimName: {{ include "owncloud.fullname" . }}
          {{- end }}
          {{- end }}
        - name: config-volume
          secret:
            secretName: owncloud-config
        {{- with .Values.owncloud.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
