{{- if .Values.persistence.owncloud.nfs.enabled -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "owncloud.fullname" . }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.owncloud.accessMode | nindent 4 }}
  capacity:
    storage: {{ .Values.persistence.owncloud.size }}
  nfs:
    server: {{ .Values.persistence.owncloud.nfs.server }}
    path: {{ .Values.persistence.owncloud.nfs.path }}
  {{- if .Values.persistence.owncloud.storageClassName }}
  {{- if (eq "-" .Values.persistence.owncloud.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.owncloud.storageClassName }}
  {{- end }}
  {{- end }}
{{end}}
{{- if .Values.persistence.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "owncloud.fullname" . }}
  {{- with .Values.persistence.owncloud.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.owncloud.accessMode | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.owncloud.size }}
  {{- if .Values.persistence.owncloud.storageClassName }}
  {{- if (eq "-" .Values.persistence.owncloud.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.owncloud.storageClassName }}
  {{- end }}
  {{- end }}
{{- end -}}
