---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb" }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "externaldb" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  db-password: {{ default "" .Values.owncloud.db.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: owncloud-config
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  configmap.config.php: |
    <?php
    {{- if .Values.owncloud.configExtra }}
    $CONFIG = json_decode('{{- toPrettyJson .Values.owncloud.configExtra | nindent 4 }}', true);
    {{- else }}
    $CONFIG = [];
    {{- end }}
